### PR TITLE
update: optimize profanity filter plugin

### PR DESCRIPTION
**Pull request by gunslinger23**
profanity filter with more efficient way

### CODE REVIEW

**Review by RainOrigami — COMMENTED** [review]
Debugging code will not be included.
Maybe the [PermissionsCommands.cs](https://github.com/RainOrigami/BattleBitBaseModules/blob/main/PermissionsCommands.cs) should have a command that lists a players permissions.

**Comment by RainOrigami** [comment]
Thanks @gunslinger23 for the improvements to the profanity filter.
Could you give a short high-level overview of how DFAState uses transitions to find profanities?

**Comment by gunslinger23** [comment]
> Thanks @gunslinger23 for the improvements to the profanity filter.
> Could you give a short high-level overview of how DFAState uses transitions to find profanities?

I let ChatGPT to explain who it works.

---

Let's consider a simple example to explain the principle of matching words using a DFA (Deterministic Finite Automaton).

Let's assume we have a DFA designed to match the English word "dog".

This DFA has three states: Start state (S), Middle state (A), and Final state (F). The start state (S) leads to the middle state (A), which can be reached by the input "d" on the transition edge. From the middle state (A), it can either loop back on the "d" transition edge or transition to the final state (F) on the "o" transition edge. The final state (F) is the accepting state with no outgoing edges.

Here is a directed graph representation of this DFA:

```
       d         o
   S -----> A -----> F
```

Now, let's assume we have an input string "dog". We start from the start state (S) and transition to the middle state (A) based on the input character "d". Then, we transition to the final state (F) based on the input character "o". Finally, we reach the end of the input string.

During this process, we perform state transitions based on the DFA's edges and the input characters. If we end at the final state (F), we can say that the input character sequence "dog" has been successfully matched by the DFA, indicating a match with the word "dog".

This example briefly illustrates the principle of matching words using a DFA: by performing state transitions based on the DFA's edges and the input string's characters, we can successfully match a specific word within the input string.

**Comment by RainOrigami** [comment]
ok thanks, will test and then release

**Pull request merged**
